language: python
python: "2.7"
sudo: false
branches:
     only:
          - master
	  - prod_sync
notifications:
  email: false
  email:
      on_failure: always
before_script: ./build/scripts/setup_credentials.sh
script: 
	if [ "$TRAVIS_BRANCH" = "master" ]; then ./build/scripts/deploy.sh
	if [ "$TRAVIS_BRANCH" = "prod_sync" ]; then ./build/scripts/pushProdSync.sh
